import { Inter } from 'next/font/google'
import './globals.css'
import { Lexend_Deca } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const lex = Lexend_Deca({subsets :['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lex.className}>{children}</body>
    </html>
  )
}
